name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
            
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Debugging-Schritt
      - name: List dist directory
        run: ls -la dist/iammichaelpeter.github.io/

      - name: Copy index.html to 404.html
        run: |
          mkdir -p dist/iammichaelpeter.github.io/browser
          cp dist/iammichaelpeter.github.io/browser/index.html dist/iammichaelpeter.github.io/browser/404.html || echo "Copy failed but continuing..."

      - name: Add .nojekyll file
        run: touch dist/iammichaelpeter.github.io/browser/.nojekyll

      # Geänderter Deploy-Schritt
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/iammichaelpeter.github.io/browser
          clean: true